select * from customer_behaviour_analysis
-- --------------------------------------------------------------------------------------------------------------------------
-- Business Insights Questions
-- --------------------------------------------------------------------------------------------------------------------------

-- 1. Which category generates highest revenue?

SELECT 
	category,
	ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM customer_behaviour_analysis
GROUP BY category
ORDER BY highest_revenue DESC

-- ❓ Business Problem :- Company does not know which category contributes most to revenue.


-- 🚀 Impact :- 
			 -- Helps prioritize high-performing categories
			 -- Optimizes inventory planning
			 -- Improves marketing ROI

-- --------------------------------------------------------------------------------------------------------------------------

-- 2. Are discounts actually increasing purchase value?

SELECT * FROM customer_behaviour_analysis

SELECT 
	discount_applied,
	ROUND(SUM(purchase_amount),2) AS total_revenue,
	ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_behaviour_analysis
GROUP BY discount_applied

-- ❓ Business Problem :- Discounts may reduce profit without increasing sales.


-- 🚀 Impact :- 
				-- Identify effectiveness of discounts
				-- Reduce unnecessary discount costs
				-- Improve profit margins

-- --------------------------------------------------------------------------------------------------------------------------
-- 3. What is the total revenue generated by male and female customer ? 
SELECT * FROM customer_behaviour_analysis

SELECT 
	gender,
	ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM customer_behaviour_analysis
GROUP BY gender
ORDER BY highest_revenue DESC


-- ❓ Business Problem :- Lack of understanding of revenue contribution by gender segments.

-- 🚀 Impact:- 
			-- Helps design targeted marketing campaigns
			-- Improves customer segmentation strategy
			-- Enhances personalization efforts

-- --------------------------------------------------------------------------------------------------------------------------

-- 4. Which customer used a discount but still spent more then the average purchase amount ?

SELECT * FROM customer_behaviour_analysis

SELECT
	customer_id,
	purchase_amount,
	discount_applied
FROM customer_behaviour_analysis
WHERE discount_applied= 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behaviour_analysis)
limit 10

-- ❓ Business Problem:- Company cannot identify high-spending customers who are also discount users.


-- 🚀 Impact:- 
			-- Identifies premium discount-sensitive customers
			-- Enables targeted discount campaigns
			-- Improves customer retention and revenue

-- --------------------------------------------------------------------------------------------------------------------------

-- 5. Which are the top/bottom 5 products with the highest average review rating. 
SELECT * FROM customer_behaviour_analysis

SELECT
	item_purchased,
	ROUND(AVG(review_rating),2) AS Avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY Avg_ratings DESC
limit 5

SELECT 
	item_purchased,
	ROUND(AVG(review_rating),2) AS Avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY Avg_ratings ASC
limit 5

-- ❓ Business Problem :- No visibility into product performance based on customer satisfaction.

-- 🚀 Impact :- 
				-- Promotes high-performing products
				-- Improves low-rated products
				-- Enhances customer experience

-- --------------------------------------------------------------------------------------------------------------------------

-- 6. Average purchase: Standard vs Express shipping

SELECT * FROM customer_behaviour_analysis

SELECT 
	shipping_type,
	COUNT(DISTINCT customer_id) as order_placed,
	ROUND(AVG(purchase_amount),2)  as avg_purchase,
	ROUND(SUM(purchase_amount),2) AS revenue
FROM customer_behaviour_analysis
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
ORDER BY revenue DESC

-- ❓ Business Problem :- Unclear if faster shipping leads to higher spending.


-- 🚀 Impact
			-- Helps optimize shipping pricing strategy
			-- Encourages premium shipping adoption
			-- Increases average order value

-- --------------------------------------------------------------------------------------------------------------------------

-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id)as users,round(avg(purchase_amount),2)as average_revenue ,
round(SUM(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by subscription_status
order by total_revenue desc;

-- --------------------------------------------------------------------------------------------------------------------------
-- top 5 product with highest disocount usage %
select item_purchased,count(case when discount_applied='Yes' then 1 else 0 end) as no_of_times_item_sold,
sum(case when discount_applied ='Yes' then 1 else 0 end) * 100.0 / count(*) as discount_usage_percent
from customer_behaviour_analysis
group by item_purchased
order by discount_usage_percent desc
limit 5
-- ❓ Business Problem :- Some products may be overly dependent on discounts.

-- 🚀 Impact:- 
 			-- Identifies discount-driven products
 			-- Helps optimize pricing strategy
 			-- Reduces profit margin loss
            
  -- --------------------------------------------------------------------------------------------------------------------------          
-- 9.Segment customer into new, returning and loyal based on their total number of previous purchase, and 
-- show the count of each segment
select customer_segment,
count(*) as total_customer_count
from
(
select case when previous_purchases = 0 then 'New_Customer'
            when previous_purchases between 1 and 5 then 'Returning_Customer'
            else 'Loyal_customer'
            end as customer_segment
from customer_behaviour_analysis) t
group by customer_segment

-- --------------------------------------------------------------------------------------------------------------------------
-- 10.what are the top 3 most purchased product with in each category
with cte as(
select category,item_purchased,count(item_purchased)as most_purchased,
rank() over(partition by category order by count(item_purchased) desc)as rnk
from customer_behaviour_analysis
group by category,item_purchased)

select *
from cte
where rnk<=3

-- --------------------------------------------------------------------------------------------------------------------------
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS customer_type,
    subscription_status,
    COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END,
    subscription_status;

-- --------------------------------------------------------------------------------------------------------------------------

-- 12. What is the revenue contribution of each age group ? 

SELECT * FROM customer_behaviour_analysis

WITH data AS (
    SELECT 
        CASE 
            WHEN age < 25 THEN 'Under 25'
            WHEN age BETWEEN 25 AND 40 THEN '25-40'
            ELSE '40+'
        END AS group_section,
        purchase_amount AS amount
    FROM customer_behaviour_analysis
)
SELECT 
    group_section,
    SUM(amount) AS total_revenue
FROM data
GROUP BY group_section
order by total_revenue desc;

-- ❓ Business Problem:- No visibility into which age group contributes most to revenue.

-- 🚀 Impact:-
			-- Enables age-based targeting
			-- Enhances marketing efficiency






